FROM node:18.20.6-alpine

WORKDIR /app
ENV NEXT_PUBLIC_SERVER_URL="http://localhost:4000"

RUN apk add --no-cache openssl

COPY . .

RUN yarn install --frozen-lockfile
RUN yarn build

EXPOSE 4000
CMD [ "yarn", "workspace", "@ledokku/server", "start" ]
