services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ledokku
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    restart: unless-stopped
    image: "redis:6"
    ports:
      - 6379:6379

volumes:
  db:
